### ISSUE TITLE
text alignment?

### ISSUE THREAD

**Issue by jonathan-chin** [BurntSushi/erd#62] opened 2019-11-01 20:17 UTC
I'm running this on OSX High Sierra, installed via Stack.

My attributes seem to be right aligned, whereas the sample pdf is left aligned. I think left aligned makes it so much easier to read.

How can I specify this? I don't think there's an option in the README.

[This is what I get](https://github.com/BurntSushi/erd/files/3799459/simple.pdf)

**Comment by mmzx** [comment] 2019-11-02 09:43
Could you perhaps paste/provide your erd file here?

**Comment by jonathan-chin** [comment] 2019-11-03 19:58
@mmzx I see it even with the example sample.er
![Screen Shot 2019-11-03 at 2 56 58 PM](https://user-images.githubusercontent.com/7519412/68091166-52b2df00-fe4a-11e9-8be2-4f17c0370980.png)

**Comment by mmzx** [comment] 2019-11-03 20:56
@jonathan-chin , currently the text alignment is hard coded, that is, node specific alignment is not supported. You could e.g. do something like the following, which is only a partial solution - because globally applied for all nodes.
`erd -i ./examples/simple.er -f dot | sed s/RIGHT/LEFT/g | dot -o"sample.pdf" -Tpdf`
Results in:
![image](https://user-images.githubusercontent.com/1039486/68091798-99252f80-fe84-11e9-8503-2b21d9983b28.png)

**Comment by jonathan-chin** [comment] 2019-11-03 21:34
@mmzx I'm also curious because my keys and node titles don't get the same styling that you do (bold, underline, italics). Is it because of my OS? because I compiled it from Stack?

**Comment by mmzx** [comment] 2019-11-03 21:45
@jonathan-chin , compiling it via stack or something else would not affect outcome.
If you would post your _erd_ file and intermediate _html_ (dot) we might understand more. I do not have access to osx, so looking at these intermediates could help.

**Comment by jonathan-chin** [comment] 2019-11-03 21:55
here is my ERD file (it's the one from the repo; just including it for completeness sake)

```
# Entities are declared in '[' ... ']'. All attributes after the entity header
# up until the end of the file (or the next entity declaration) correspond
# to this entity.
[Person]
*name
height
weight
`birth date`
+birth_place_id

[`Birth Place`]
*id
`birth city`
'birth state'
"birth country"

# Each relationship must be between exactly two entities, which need not
# be distinct. Each entity in the relationship has exactly one of four
# possible cardinalities:
#
# Cardinality    Syntax
# 0 or 1         ?
# exactly 1      1
# 0 or more      *
# 1 or more      +
Person *--1 `Birth Place`
```

here (I believe) is the dot file generated by `erd -i ./simple.er -f dot > simple.dot`

```
graph {
	graph [rankdir=LR,
		splines=spline
	];
	node [label="\N",
		shape=plaintext
	];
	edge [color=gray50,
		minlen=2,
		style=dashed
	];
	Person	 [label=<<FONT FACE="Helvetica"><TABLE BORDER="0" CELLBORDER="1" CELLPADDING="4" CELLSPACING="0"><TR><TD><B><FONT POINT-SIZE="16">Person</FONT></B></TD></TR><TR><TD ALIGN="RIGHT"><U><FONT>name</FONT></U></TD></TR><TR><TD ALIGN="RIGHT"><FONT>height</FONT></TD></TR><TR><TD ALIGN="RIGHT"><FONT>weight</FONT></TD></TR><TR><TD ALIGN="RIGHT"><FONT>birth date</FONT></TD></TR><TR><TD ALIGN="RIGHT"><I><FONT>birth_place_id</FONT></I></TD></TR></TABLE></FONT>>];
	"Birth Place"	 [label=<<FONT FACE="Helvetica"><TABLE BORDER="0" CELLBORDER="1" CELLPADDING="4" CELLSPACING="0"><TR><TD><B><FONT POINT-SIZE="16">Birth Place</FONT></B></TD></TR><TR><TD ALIGN="RIGHT"><U><FONT>id</FONT></U></TD></TR><TR><TD ALIGN="RIGHT"><FONT>birth city</FONT></TD></TR><TR><TD ALIGN="RIGHT"><FONT>birth state</FONT></TD></TR><TR><TD ALIGN="RIGHT"><FONT>birth country</FONT></TD></TR></TABLE></FONT>>];
	Person -- "Birth Place"	 [headlabel=<<FONT>1</FONT>>,
		taillabel=<<FONT>0..N</FONT>>];
}
```

**Comment by mmzx** [comment] 2019-11-05 08:48
The _dot_ file is correct, generated as it should be. So my assumption will be that it is your local setup that contributes to the differences.
What is your version of _dot (dot -V)_?
Maybe you could try other output format(s), e.g. svg, which can be checked in a web-browser.

**Comment by jonathan-chin** [comment] 2019-11-05 17:09
Thanks. I do notice that in the dot file, there's `<TD ALIGN="RIGHT">`

my dot version is `dot - graphviz version 2.40.1 (20161225.0304)`

I also just tried some other output formats (png, jpg, gif, svg, pdf) and it's the same. right aligned, no other styling on keys.

**Comment by mmzx** [comment] 2019-11-05 19:41
- The default is to generate right aligned text, that is what is shown in your generated _erd_ file.

- Currently it is not supported to change the alignment of the text by _erd_ via command or by other means. 

- Would you want to change the alignment of the text, via the above suggested workaround (using _sed_) you shall be able to do that. It is to be expected to bring provide you different output when applied correctly.

- Your _graphviz_ version is excellent.

Other than that, if all above fails I would say it has something to do with the local setup of yours.

Have you tried the above workaround with _sed_?

**Comment by jonathan-chin** [comment] 2019-11-05 19:59
@mmzx the above workaround works for left aligning but the primary and foreign keys are not being formatted. I noticed this in the README:

`NB OSX users: for text formatting of keys (bold and italics) you may need to reinstall graphviz with pango support:`

However, after doing what it suggested (`brew install graphviz`), the keys are still not formatted. is the issue (alignment and formatting) with pango support?

**Comment by jonathan-chin** [comment] 2019-12-03 09:09
following up on this. I installed ERD on a new machine (completely different from previous). Now running Ubuntu 18.04LTS

color and styling work but everything is right aligned like before. this happens, again, with just the sample ERD file.

**Comment by mmzx** [comment] 2019-12-03 20:02
Okay. I had some commits that were not pushed from recent days. It is now explicitly defined to align to the left, which is the default anyway.
Could you please check again? You would need to build `erd` by cloning the master branch and building a binary.
```
git clone https://github.com/BurntSushi/erd.git
cd erd
stack build     # or install
```

**Comment by jonathan-chin** [comment] 2019-12-04 11:52
thanks @mmzx ! my ubuntu system works perfectly now.
on osx, the text alignment is fixed but some of the other styling isn't showing through (underlining and italics primary / foreign keys). this is the example simple.er:

![simple](https://user-images.githubusercontent.com/7519412/70140216-3e891a00-1662-11ea-9d03-14c49386c2fb.png)

any idea why? it's not a dealbreaker; honestly, the text alignment was a deal breaker and I was *just* about to learn graphwiz myself, but now I think I'll stick with erd.

I'd love to help but I dived into the source code yesterday and realized I have no idea how Haskell works.

**Comment by mmzx** [comment] 2019-12-04 21:48
Yeah, stick with **erd**! :P
I suspect these differences are related to local settings, which I think is inherently difficult to be prepared for. There is some work/idea in preparation to explicitly define more of these properties. In such situations we should compare output files. So, the resulted **dot** file is the following via the command `erd -i simple.er  -f dot` on my machine:
```
graph {
        graph [rankdir=LR,
                splines=spline
        ];
        node [label="\N",
                shape=plaintext
        ];
        edge [color=gray50,
                minlen=2,
                style=dashed
        ];
        Person   [label=<<FONT FACE="Helvetica"><TABLE BORDER="0" CELLBORDER="1" CELLPADDING="4" CELLSPACING="0"><TR><TD><B><FONT POINT-SIZE="16">Person</FONT></B></TD></TR><TR><TD ALIGN="LEFT"><U><FONT>name</FONT></U></TD></TR><TR><TD ALIGN="LEFT"><FONT>height</FONT></TD></TR><TR><TD ALIGN="LEFT"><FONT>weight</FONT></TD></TR><TR><TD ALIGN="LEFT"><FONT>birth date</FONT></TD></TR><TR><TD ALIGN="LEFT"><I><FONT>birth_place_id</FONT></I></TD></TR></TABLE></FONT>>];
        "Birth Place"    [label=<<FONT FACE="Helvetica"><TABLE BORDER="0" CELLBORDER="1" CELLPADDING="4" CELLSPACING="0"><TR><TD><B><FONT POINT-SIZE="16">Birth Place</FONT></B></TD></TR><TR><TD ALIGN="LEFT"><U><FONT>id</FONT></U></TD></TR><TR><TD ALIGN="LEFT"><FONT>birth city</FONT></TD></TR><TR><TD ALIGN="LEFT"><FONT>birth state</FONT></TD></TR><TR><TD ALIGN="LEFT"><FONT>birth country</FONT></TD></TR></TABLE></FONT>>];
        Person -- "Birth Place"  [headlabel=<<FONT>1</FONT>>,
                taillabel=<<FONT>0..N</FONT>>];
}
```
Interpreting the **dot** file goes beyond `erd` itself. I will try to see whether I can find out more about it, but I myself can't reproduce the issue.

I am happy that your alignment issue is resolved then!

**Comment by jonathan-chin** [comment] 2019-12-05 00:30
here's what I get with the same command:

```
graph {
	graph [rankdir=LR,
		splines=spline
	];
	node [label="\N",
		shape=plaintext
	];
	edge [color=gray50,
		minlen=2,
		style=dashed
	];
	Person	 [label=<<FONT FACE="Helvetica"><TABLE BORDER="0" CELLBORDER="1" CELLPADDING="4" CELLSPACING="0"><TR><TD><B><FONT POINT-SIZE="16">Person</FONT></B></TD></TR><TR><TD ALIGN="LEFT"><U><FONT>name</FONT></U></TD></TR><TR><TD ALIGN="LEFT"><FONT>height</FONT></TD></TR><TR><TD ALIGN="LEFT"><FONT>weight</FONT></TD></TR><TR><TD ALIGN="LEFT"><FONT>birth date</FONT></TD></TR><TR><TD ALIGN="LEFT"><I><FONT>birth_place_id</FONT></I></TD></TR></TABLE></FONT>>];
	"Birth Place"	 [label=<<FONT FACE="Helvetica"><TABLE BORDER="0" CELLBORDER="1" CELLPADDING="4" CELLSPACING="0"><TR><TD><B><FONT POINT-SIZE="16">Birth Place</FONT></B></TD></TR><TR><TD ALIGN="LEFT"><U><FONT>id</FONT></U></TD></TR><TR><TD ALIGN="LEFT"><FONT>birth city</FONT></TD></TR><TR><TD ALIGN="LEFT"><FONT>birth state</FONT></TD></TR><TR><TD ALIGN="LEFT"><FONT>birth country</FONT></TD></TR></TABLE></FONT>>];
	Person -- "Birth Place"	 [headlabel=<<FONT>1</FONT>>,
		taillabel=<<FONT>0..N</FONT>>];
}
```

So our dot's are the same. What's the next step in processing?

**Comment by mmzx** [comment] 2019-12-08 16:54
I have just done some searching in the hope there will be straightforward answer(s). I believe we are dealing with the same type of situation as described in [1].

The content of the dot file match up against the expected content: that's how far `erd` itself can go; the rendered result may differ based on platform related differences.

My current recommendation for the short therm would be to stick with something that works as expected. Alternatively _docker_ or the statically built version of `erd` [2]. On the long-term, we would need to see whether this can be influenced and, first of all, to be reproduced.

In [2] now, there are binaries for 64bit systems statically and dynamically linked ones. I do understand that it would not solve osx related issues, but the static binary is there for the purpose to have something which behaves equally well.

[1, stackoverflow; graphviz](https://stackoverflow.com/questions/58644879/dot-graphviz-node-labels-not-displaying-html-like-subscripts)

[2, v0.2.1.0-RC1](https://github.com/BurntSushi/erd/releases/tag/v0.2.1.0-RC1)

**Comment by jonathan-chin** [comment] 2019-12-08 17:02
thanks! the other stylings aren't deal breakers but the alignment was.

**Comment by mmzx** [comment] 2019-12-08 18:10
If you could help finding out the dirty details that would be great at least to know the reasons to have an explanation.

**Comment by jonathan-chin** [comment] 2019-12-08 18:30
I'm not sure where to begin. what happens to the dot file after it's generated? if I know that, I could pick up the line of investigation.

**Comment by mmzx** [comment] 2019-12-09 16:43
I have created a [ticket](https://gitlab.com/graphviz/graphviz/issues/1636), hopefully we will gain some insights.

**Comment by mmzx** [comment] 2019-12-09 16:46
I have created a [ticket](https://gitlab.com/graphviz/graphviz/issues/1636), hopefully we will gain some insights.

**Comment by mmzx** [comment] 2019-12-09 18:38
@jonathan-chin , would you mind if you (we) continue the discussion on the gitlab ticket, specifically anything that is related to *dot* itself?

**Comment by mmzx** [comment] 2019-12-11 21:52
Hell, yeah! Thank you!

I am going to update the readme based on the inputs you have kindly provided.
If you think all of your issues has been resolved, I would like to close this. Please let me know!

**Comment by jonathan-chin** [comment] 2019-12-11 21:53
my issues have been solved!

**Closed** 2019-12-11 22:02 UTC
