### ISSUE TITLE
Resolving dependencies on Windows

### ISSUE THREAD

**Issue by khalid-hussain** [BurntSushi/erd#17] opened 2016-01-20 09:25 UTC
I'm getting the following error on Windows. I've installed it from source, installed GraphViz, and set the path for the latter's `bin` directory as well; I know it is working as `dot -V` gives me correct output.
```
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
trying: erd-0.1.3.0 (user goal)
next goal: base (dependency of erd-0.1.3.0)
rejecting: base-4.8.2.0/installed-140... (conflict: erd => base==4.7.*)
rejecting: base-4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0,
4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1,
4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires
installed instance)
Dependency tree exhaustively searched.
```

I've also tried running the command after using the `cabal update` command. Any ideas?

Thanks for your time.

**Comment by BurntSushi** [comment] 2016-01-20 11:35
Dupe of #14 unfortunately.

I need to try a release again. When I tried before, the new version of GHC wasn't compatible with all dependencies (graphviz in particular) and I saw no easy way to fix it. Maybe this has changed.

**Closed by BurntSushi** 2016-01-20 11:35 UTC
